import { useState } from 'react'
import { Link, NavLink, Route, Routes } from 'react-router-dom'
import { ArrowRight, Command, Menu, MessageCircle, Search, ShieldCheck, Sparkles, X } from 'lucide-react'
import { AuthProvider, RequireRole, SignOut, useAuth } from './context/AuthContext'
import { Account, Profile } from './pages/Account'
import { HostelDetail, Hostels } from './pages/Student'
import Admin from './pages/Admin'
import Messages from './pages/Messages'
import { Page } from './components/ui'

const ownerPortal = import.meta.env.VITE_OWNER_PORTAL_URL || 'https://hostel-site-admin.vercel.app'
function Logo() { return <Link to="/" className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-zinc-950 text-white"><Command size={18} /></span><span className="text-[15px] font-semibold tracking-tight">hostel<span className="text-zinc-400">hub</span></span></Link> }
function Shell({ children }) {
  const { user, loading } = useAuth()
  const [open, setOpen] = useState(false)
  const links = [['/hostels', 'Find a hostel'], ...(user?.role === 'STUDENT' ? [['/favorites', 'Saved'], ['/messages', 'Messages']] : []), ...(user?.role === 'ADMIN' ? [['/admin', 'Administration']] : []), ...(user ? [['/profile', user.name]] : [['/login', 'Sign in']])]
  const navigation = <>{links.map(([to, label]) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className="rounded-lg px-3 py-2 text-xs font-medium text-zinc-600 hover:bg-zinc-100">{label}</NavLink>)}{user && <SignOut />}</>
  return <><header className="sticky top-0 z-40 border-b border-zinc-200 bg-[#fafafa]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-[72px] max-w-[1240px] items-center justify-between gap-4 px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-1 md:flex">{!loading && navigation}</nav><button aria-label="Open navigation" onClick={() => setOpen(true)} className="rounded-xl border border-zinc-200 bg-white p-3 md:hidden"><Menu size={18} /></button></div></header>{children}{open && <div className="fixed inset-0 z-50 bg-zinc-950/20 backdrop-blur-sm md:hidden"><button aria-label="Close navigation" className="absolute inset-0" onClick={() => setOpen(false)} /><aside className="absolute inset-y-0 right-0 w-[290px] bg-white p-5"><div className="flex justify-between"><Logo /><button aria-label="Close navigation" onClick={() => setOpen(false)}><X size={18} /></button></div><nav className="mt-10 grid gap-3">{navigation}<a className="px-3 py-2 text-xs font-semibold" href={ownerPortal}>Owner portal</a></nav></aside></div>}</>
}
function Landing() {
  return <div><section className="mx-auto grid max-w-[1240px] gap-10 px-5 pb-20 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-white px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[.14em] text-zinc-500"><Sparkles size={13} />A better way to find home</div><h1 className="text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-[76px]">Find a place that feels like <span className="text-zinc-400">home.</span></h1><p className="mt-7 max-w-[490px] text-base leading-7 text-zinc-500">Explore approved hostels, save your favorite spaces and connect directly with their owners.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/hostels" className="action-link">Explore hostels <ArrowRight size={16} /></Link><a href={ownerPortal} className="inline-flex h-12 items-center rounded-xl border border-zinc-200 bg-white px-5 text-sm font-semibold text-zinc-700">List your property</a></div></div><div className="relative"><div className="absolute -inset-3 rounded-[32px] bg-zinc-200/50 blur-2xl" /><div className="relative overflow-hidden rounded-[28px] border border-white bg-zinc-200 shadow-2xl shadow-zinc-300/40"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85" className="h-[430px] w-full object-cover sm:h-[540px]" alt="A bright living space" /><div className="absolute inset-x-5 bottom-5 rounded-2xl border border-white/60 bg-white/90 p-5 backdrop-blur-md"><p className="text-xs font-medium text-zinc-500">Space for your next chapter</p><p className="mt-2 text-sm font-semibold">Find room to study, rest and belong.</p></div></div></div></section><section className="mx-auto max-w-[1240px] px-5 pb-20 lg:px-8"><p className="eyebrow">Simple by design</p><h2 className="section-title">Your next chapter starts here.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{[[Search, '01', 'Search with clarity', 'Filter by city, budget and the amenities you need.'], [ShieldCheck, '02', 'Choose with confidence', 'Explore listings that have passed administrator review.'], [MessageCircle, '03', 'Move forward faster', 'Chat directly with owners and arrange a visit.']].map(([Icon, number, title, description]) => <div key={number} className="panel"><div className="flex items-center justify-between"><span className="rounded-xl bg-zinc-100 p-3"><Icon size={18} /></span><span className="text-xs text-zinc-400">{number}</span></div><h3 className="mt-7 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{description}</p></div>)}</div></section></div>
}
export default function App() {
  return <AuthProvider><Shell><Routes><Route path="/" element={<Landing />} /><Route path="/login" element={<Account />} /><Route path="/register" element={<Account key="register" />} /><Route path="/hostels" element={<Hostels />} /><Route path="/hostels/:id" element={<HostelDetail />} /><Route path="/favorites" element={<RequireRole roles={['STUDENT']}><Hostels key="favorites" favorites /></RequireRole>} /><Route path="/messages" element={<RequireRole roles={['STUDENT']}><Messages /></RequireRole>} /><Route path="/profile" element={<RequireRole roles={['STUDENT', 'OWNER', 'ADMIN']}><Profile /></RequireRole>} /><Route path="/admin/*" element={<RequireRole roles={['ADMIN']}><Admin /></RequireRole>} /><Route path="/owner/*" element={<Page eyebrow="Property management" title="Owner workspace" description="Manage your listings and student conversations in the dedicated owner portal."><a href={ownerPortal} className="action-link">Open owner portal <ArrowRight size={16} /></a></Page>} /><Route path="*" element={<Page title="Page not found"><Link to="/" className="action-link">Back home</Link></Page>} /></Routes></Shell></AuthProvider>
}
