import { test, expect } from '@playwright/test'

const studentURL = 'http://localhost:5173'
const ownerURL = 'http://localhost:5174'
const password = 'Browser-testing-123!'
async function login(page, base, username) {
  await page.goto(`${base}/login`)
  await page.getByLabel('Username or email').fill(username)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
}
test('student, owner and admin persist a complete hostel workflow across portals', async ({ browser }) => {
  const contexts = await Promise.all([browser.newContext(), browser.newContext({ viewport: { width: 390, height: 844 } }), browser.newContext()])
  const [owner, student, admin] = await Promise.all(contexts.map(context => context.newPage()))
  const browserErrors = []
  for (const page of [owner, student, admin]) page.on('pageerror', error => browserErrors.push(error.message))
  try {
    await owner.goto(`${ownerURL}/register`)
    await owner.getByLabel('Full name').fill('Browser Owner')
    await owner.getByLabel('Email', { exact: true }).fill('owner@browser.example')
    await owner.getByLabel('Username', { exact: true }).fill('browser_owner')
    await owner.getByLabel('Password', { exact: true }).fill(password)
    await owner.getByLabel('Confirm password').fill(password)
    await owner.getByRole('button', { name: 'Create owner account' }).click()
    await expect(owner.getByRole('heading', { name: 'Welcome, Browser.' })).toBeVisible()
    await owner.goto(`${ownerURL}/hostel`)
    await owner.getByRole('button', { name: 'Create listing' }).click()
    await owner.getByLabel('Hostel name').fill('Browser Campus Lodge')
    await owner.getByLabel('City', { exact: true }).fill('Lahore')
    await owner.getByLabel('Full address').fill('12 Campus Road')
    await owner.getByLabel('Description', { exact: true }).fill('A quiet residence for students close to campus.')
    await owner.getByLabel('Monthly price (PKR)').fill('24000')
    await owner.getByLabel('Available beds').fill('4')
    await owner.getByLabel('Amenities (comma separated)').fill('WiFi, Laundry')
    await owner.getByRole('button', { name: 'Save draft', exact: true }).click()
    await expect(owner.getByRole('status')).toContainText('Draft saved')
    const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aO2sAAAAASUVORK5CYII=', 'base64')
    await owner.getByLabel('Upload photos').setInputFiles([{ name: 'room.png', mimeType: 'image/png', buffer: image }, { name: 'study.png', mimeType: 'image/png', buffer: image }])
    await expect(owner.getByRole('status')).toContainText('Photos uploaded')
    await owner.getByRole('button', { name: 'Make cover' }).click()
    await expect(owner.getByRole('status')).toContainText('Photo settings saved')
    await owner.getByRole('button', { name: 'Move photo 2 earlier' }).click()
    await expect(owner.getByRole('button', { name: 'Submit for review' })).toBeEnabled()
    await owner.getByRole('button', { name: 'Submit for review' }).click()
    await expect(owner.getByRole('status')).toContainText('Submitted')
    await owner.reload()
    await expect(owner.getByText('PENDING', { exact: true })).toBeVisible()

    await login(admin, studentURL, 'admin@browser.example')
    await admin.getByRole('link', { name: 'Hostels', exact: true }).click()
    await expect(admin.getByRole('heading', { name: 'Browser Campus Lodge' })).toBeVisible()
    await admin.getByRole('button', { name: 'Approve', exact: true }).click()
    await expect(admin.getByText('No listings in this queue.')).toBeVisible()

    await student.goto(`${studentURL}/register`)
    await student.getByLabel('Full name').fill('Browser Student')
    await student.getByLabel('Email', { exact: true }).fill('student@browser.example')
    await student.getByLabel('Password', { exact: true }).fill(password)
    await student.getByLabel('Confirm password').fill(password)
    await student.getByRole('button', { name: 'Create student account' }).click()
    await expect(student.getByRole('heading', { name: 'Find your next place.' })).toBeVisible()
    await student.getByLabel('City', { exact: true }).fill('Lahore')
    await student.getByRole('button', { name: 'Search', exact: true }).click()
    await student.getByRole('link', { name: /Browser Campus Lodge/ }).click()
    await student.getByRole('button', { name: 'Save to favorites' }).click()
    await student.reload()
    await expect(student.getByRole('button', { name: 'Remove from favorites' })).toBeVisible()
    await student.getByRole('button', { name: 'Message owner' }).click()
    await student.getByLabel('Message', { exact: true }).fill('Is a room available?')
    await student.getByRole('button', { name: 'Send', exact: true }).click()
    await expect(student.getByText('Is a room available?', { exact: true }).last()).toBeVisible()
    await owner.goto(`${ownerURL}/messages`)
    await owner.getByRole('button', { name: /Browser Student/ }).click()
    await expect(owner.getByText('Is a room available?', { exact: true }).last()).toBeVisible()
    await owner.getByLabel('Message', { exact: true }).fill('Yes, you can visit tomorrow.')
    await owner.getByRole('button', { name: 'Send', exact: true }).click()
    await expect(student.getByText('Yes, you can visit tomorrow.', { exact: true }).last()).toBeVisible()
    await student.reload()
    await expect(student.getByText('Yes, you can visit tomorrow.', { exact: true }).last()).toBeVisible()
    await student.goto(`${studentURL}/profile`)
    await student.getByLabel('Full name').fill('Updated Student')
    await student.getByRole('button', { name: 'Save changes' }).click()
    await expect(student.getByRole('status')).toContainText('saved')
    await student.reload()
    await expect(student.getByLabel('Full name')).toHaveValue('Updated Student')
    await student.goto(`${studentURL}/admin`)
    await expect(student.getByRole('heading', { name: 'Access restricted' })).toBeVisible()
    await admin.goto(`${studentURL}/admin/users`)
    const account = admin.locator('.panel').filter({ hasText: 'owner@browser.example' })
    await account.getByRole('button', { name: 'Suspend account' }).click()
    await owner.reload()
    await expect(owner.getByRole('heading', { name: 'Sign in.' })).toBeVisible()
    await student.goto(`${studentURL}/hostels`)
    await expect(student.getByText('No matching hostels. Try changing your filters.')).toBeVisible()
    expect(browserErrors).toEqual([])
  } finally { await Promise.all(contexts.map(context => context.close())) }
})
